# version: '3.3'
services:
  mongodb:
    image: mongo:4.4
    container_name: dstair_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dstairlines
      MONGO_INITDB_ROOT_PASSWORD: dstairlines
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017