# version: '3.3'
services:
  app_admin:
    image: guillaumegossmann/dst_airlines_app_admin:latest
    container_name: dstair_app_admin
    depends_on:
      - mongodb
    ports:
      - "8888:8888"  # Port pour Jupyter Notebook
      - "5000:5000"  # Port pour flask
    volumes:
      - ./app_admin/scripts:/app/scripts
      - ./model:/app/model
      - ./data_test:/app/data_test
      - ./functions:/app/functions
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - API_KEY=${API_KEY}
      - KEY_AS=${KEY_AS}
      - KEY_VISUALCROSSING=${KEY_VISUALCROSSING}
      - KEY_VISUALCROSSING_2=${KEY_VISUALCROSSING_2}
      - CLIENT_ID_LH=${CLIENT_ID_LH}
      - CLIENT_SECRET_LH=${CLIENT_SECRET_LH}
    command: ./start.sh