# version: '3.3'
services:
  mongodb:
    image: mongo:4.4
    container_name: dstair_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
    # ports:
    #   - 27017:27017
    networks:
      - dstair_network
      
  flask_app:
    image: guillaumegossmann/dst_airlines_app:latest
    container_name: dstair_flask_app
    ports:
      - 5002:5002
    depends_on:
      - mongodb
    volumes:
      - ./model:/app/model  # Volume partagé avec l'hôte
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - API_KEY=${API_KEY}
    command: python app.py
    networks:
      - dstair_network

  flask_app_form:
    image: guillaumegossmann/dst_airlines_app_form:latest
    container_name: dstair_flask_app_form
    depends_on:
      - mongodb
    ports:
      - 5001:5001
    volumes:
      - ./functions:/app/functions
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY_FORM=${FLASK_SECRET_KEY_FORM}
      - API_KEY=${API_KEY}
      - KEY_AS=${KEY_AS}
      - KEY_VISUALCROSSING=${KEY_VISUALCROSSING}
      - KEY_VISUALCROSSING_2=${KEY_VISUALCROSSING_2}
      - CLIENT_ID_LH=${CLIENT_ID_LH}
      - CLIENT_SECRET_LH=${CLIENT_SECRET_LH}
    command: python app.py
    networks:
      - dstair_network

  app_admin:
    image: guillaumegossmann/dst_airlines_app_admin:latest
    container_name: dstair_app_admin
    depends_on:
      - mongodb
    ports:
      - "8888:8888"  # Port pour Jupyter Notebook
      - "5000:5000"  # Port pour flask
    volumes:
      - ./app_admin/scripts:/app/scripts
      - ./model:/app/model
      - ./data_test:/app/data_test
      - ./functions:/app/functions
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - API_KEY=${API_KEY}
      - KEY_AS=${KEY_AS}
      - KEY_VISUALCROSSING=${KEY_VISUALCROSSING}
      - KEY_VISUALCROSSING_2=${KEY_VISUALCROSSING_2}
      - CLIENT_ID_LH=${CLIENT_ID_LH}
      - CLIENT_SECRET_LH=${CLIENT_SECRET_LH}
    command: ./start.sh
    networks:
      - dstair_network
    
  app_dash:
    image: guillaumegossmann/dst_airlines_app_dash:latest
    container_name: dstair_app_dash
    depends_on:
      - mongodb
    ports:
      - "8051:8051"  # Port pour Dash
    volumes:
      - ./model:/app/model
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    command: python app.py
    networks:
      - dstair_network

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    # image: percona/mongodb_exporter:latest
    container_name: dstair_mongodb_exporter
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017
    ports:
      - 9216:9216
    depends_on:
      - mongodb
    networks:
      - dstair_network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: dstair_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - mongodb_exporter
      - cadvisor
    networks:
      - dstair_network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: dstair_grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - dstair_network
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - dstair_network
    restart: always
    # deploy:
    #   mode: global

volumes:
  grafana_data:

networks:
  dstair_network:
    external: true