# version: '3.3'
services:
  app_dash:
    image: guillaumegossmann/dst_airlines_app_dash:latest
    container_name: dstair_app_dash
    depends_on:
      - mongodb
    ports:
      - "8051:8051"  # Port pour Dash
    volumes:
      - ./model:/app/model
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    command: python app.py