# version: '3.3'
services:
  flask_app_form:
    image: guillaumegossmann/dst_airlines_app_form:latest
    container_name: dstair_flask_app_form
    ports:
      - 5001:5001
    volumes:
      - ./functions:/app/functions
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_LOGIN}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app_data?authSource=admin
      #?authSource=admin -> on précise que l'on s'authentifie sur la base admin, car mongo créer les utilisateurs dans admin par défaut
      - FLASK_ADMIN_LOGIN=${FLASK_ADMIN_LOGIN}
      - FLASK_ADMIN_PASSWORD=${FLASK_ADMIN_PASSWORD}
      - FLASK_USER_LOGIN=${FLASK_USER_LOGIN}
      - FLASK_USER_PASSWORD=${FLASK_USER_PASSWORD}
      - FLASK_SECRET_KEY_FORM=${FLASK_SECRET_KEY_FORM}
      - API_KEY=${API_KEY}
      - KEY_AS=${KEY_AS}
      - KEY_VISUALCROSSING=${KEY_VISUALCROSSING}
      - KEY_VISUALCROSSING_2=${KEY_VISUALCROSSING_2}
      - CLIENT_ID_LH=${CLIENT_ID_LH}
      - CLIENT_SECRET_LH=${CLIENT_SECRET_LH}
    command: python app.py
    networks:
      - shared_net

networks:
  shared_net:
    external: true