global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "cadvisor"
    # Remplacez la valeur globale par défaut et récupérez les cibles de cette tâche toutes les 5 secondes.
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: 'mongodb'
    static_configs:
      - targets: ['dstair_mongodb_exporter:9216']

  - job_name: 'node_exporter'
    static_configs:
      # - targets: ['host.docker.internal:9100'] # host.docker.internal car le node explorer sera installé sur notre VM de prod
      - targets: ['172.19.0.1:9100'] # 172.19.0.1 adresse de la gateway docker du dstair_network

  - job_name: 'flask_app_form'
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['dstair_flask_app_form:5001']
